version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  severity: high
    #target-branch: "dependabot"  # Replace with your desired branch name
  #  reviewers:
   #   - "ismail0352"
    allow:
      - dependency-type: "all"
